server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 将实例注册到这些个url地址,
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    # 是否注册: 是
    register-with-eureka: true
    # 是否检索服务: 是, 单节点无所谓, 集群环境必须为true才能配合ribbon使用负载均衡
    fetch-registry: true