server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #服务实例名称, 在eureka注册中心可以看到这个名字, 如果注册到eureka的话
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://103.192.179.239:3306/springcloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: z?guwrBhH7p>
    druid:
      validation-query: select 1
      test-while-idle: true
  devtools:
    add-properties: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lisen.springcloud.com.lisen.springcloud.entities    # 所有Entity别名类所在包

eureka:
  client:
    # 将实例注册到这些个url地址,
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
    # 是否注册: 是
    register-with-eureka: true
    # 是否检索服务: 是, 单节点无所谓, 集群环境必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
  instance:
    # 优化注册中心的显示信息, 各个服务实例名称修改
    instance-id: payment8001
    # 访问信息有ip提示
    prefer-ip-address: true
    # Eureka 客户端向服务器发送心跳的时间间隔, 单位为秒(默认30s)
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待时间上限, 单位为秒(默认90s)
    lease-expiration-duration-in-seconds: 2