server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 127.0.0.1
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://103.192.179.239:3306/springcloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: z?guwrBhH7p>
    druid:
      validation-query: select 1
      test-while-idle: true
