server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment #服务实例名称, 注册zookeeper到注册中心
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://103.192.179.239:3306/springcloud-2020?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: z?guwrBhH7p>
    druid:
      validation-query: select 1
      test-while-idle: true
  devtools:
    add-properties: true
  cloud:
    zookeeper:
      connect-string: 103.192.179.239:2181

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lisen.springcloud.com.lisen.springcloud.entities    # 所有Entity别名类所在包
